export const HOME = '/'
export const BROWSE = '/browse'
export const CART = '/cart'
export const CHECKOUT = '/checkout'
export const PAYMENT = '/payment'
export const ABOUT = '/about'
export const CONTACT = '/contact'